Repository nnethercott/hannoy, pull requests merged in 2025-08, with the labels that each got.

#59 test: add criterion benchmarks
  .github/workflows/codspeed.yml
  Cargo.toml
  benches/benchmark.rs
  docs/benchmarks/arroy_hannoy.md
  docs/benchmarks/cosine_hamming.md
  example/src/main.rs
Labels: benchmarks

#66 Use linear search when small number of candidates to search in
  src/reader.rs
Labels: enhancement

#67 docs: clean up the rust docs
  README.md
  example/Cargo.toml
  example/src/main.rs
  src/distance/binary_quantized_cosine.rs
  src/distance/binary_quantized_euclidean.rs
  src/distance/binary_quantized_manhattan.rs
  src/distance/cosine.rs
  src/distance/euclidean.rs
  src/distance/manhattan.rs
  src/distance/mod.rs
  src/error.rs
  src/key.rs
  src/lib.rs
  src/node.rs
  src/node_id.rs
  src/parallel.rs
  src/reader.rs
  src/writer.rs
Labels: documentation
